// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DownloadManager.Models;

#nullable disable

namespace DownloadManager.Data
{
    public partial class DownloadContext : DbContext
    {
        public DownloadContext()
        {
        }

        public DownloadContext(DbContextOptions<DownloadContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite("Data Source=./mydb.db");
            }
        }

        public virtual DbSet<Downloads> Downloads { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Downloads>(entity =>
            {
                entity.HasKey(e => e.FileId);

               

                entity.Property(e => e.Url).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}